# Configuration file for the python module NBJoint for the machinelearning_notes
# Arquivo de configuração do módulo NBJoint para as notas de Modelagem Matemática

version: 0.13a

path_to_notes: ../notebooks

contents:
  toc_nb_name: 00.00-Pagina_inicial.ipynb
  toc_title: Sumário
  show_index_in_toc: True

header: "*Tutorial sobre Flux.jl - 2020/2 [- Ricardo M. S. Rosa (IM/UFRJ)](http://www.im.ufrj.br/rrosa)*"

navigators:
  core_navigators:
    - 00.00-Pagina_inicial.ipynb
  show_nb_title_in_nav: True
  show_index_in_nav: True

badges:
  - title: View in NBViewer
    url: https://nbviewer.jupyter.org/github/rmsrosa/TutorialFlux/blob/main/notebooks
    label: view in
    message: nbviewer
    color: orange
  - title: Open in binder
    url: https://mybinder.org/v2/gh/rmsrosa/TutorialFlux/julia-env-for-binder?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Frmsrosa%252FTutorialFlux%26branch%3Dmain%26urlpath%3Dtree%252FTutorialFlux%252Fnotebooks
    src: https://mybinder.org/badge.svg
  - title: View Slides
    url: https://nbviewer.jupyter.org/github/rmsrosa/TutorialFlux/blob/main/notebooks/slides
    extension: .slides.html
    label: view
    message: slides
    color: darkgreen
    
exports:
  - export_path: ../notebooks/slides
    exporter_name: slides
    exporter_args:
      reveal_scroll: True
#      TemplateExporter.extra_template_basedirs: /Users/rrosa/Documents/git_repositories/modelagem_matematica/tools
#      template: "/Users/rrosa/Documents/git_repositories/modelagem_matematica/tools/output_toggle.tpl"
      